"""rename address

Revision ID: 36f588e3e93d
Revises: 77c82bcc56da
Create Date: 2025-06-13 09:03:12.355851

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '36f588e3e93d'
down_revision = '77c82bcc56da'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
     op.alter_column('departments', 'address',  new_column_name='location')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
     op.alter_column('departments', 'location',  new_column_name='address')
    # ### end Alembic commands ###
